---
- apt: name={{ item }} state=latest update_cache=yes
  with_items:
    - build-essential
    - git
    - libxml2-dev
    - libxslt1-dev
    - python-dev
    - python-pip

- synchronize: src=../../../../ archive=no dest=/home/stack/taas delete=yes  recursive=yes

- file: path=/home/stack/taas owner=stack group=stack mode=775

- pip: requirements='https://raw.githubusercontent.com/jpmontez/taas/master/requirements.txt'
       state=latest
